name: Release
on: 
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run build
      - uses: codfish/semantic-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
